name: Sync Wiki to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Checkout wiki repo
        uses: actions/checkout@v3
        with:
          repository: brdbank/best-practices.wiki
          path: wiki

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdown converter
        run: npm install -g markdown-to-html-cli

      - name: Convert markdown to HTML
        run: |
          mkdir -p site/wiki
          for file in wiki/*.md; do
            filename=$(basename "$file" .md)
            markdown-to-html "$file" -o "site/wiki/${filename}.html"
          done

      - name: Copy static HTML (optional)
        run: |
          cp -r static/* site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
